### ISSUE TITLE
Add Style for Selected Inputs

### ISSUE THREAD

**Issue by luisjrez** [luisjrez/RN-Template-eCommerce-#3]
![Selected_Input](https://user-images.githubusercontent.com/78288250/138803505-f6e0331e-b7be-4f9c-a95c-5e5f3e2b91ac.jpeg)

- The inputs should look like in the picture above

**Comment by jblancoh** [comment]
Can you assigned me this issue???

**Comment by luisjrez** [comment]
can add you some input mask to add the correct format on the inputs @jblancoh happy hacking!
